# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e008df4caedb714073c5eabe61ab2466df51785ed9e283ba9b5d6dbee8ae10b63b8f5ea5965593d206d2246f86960a22c020547a3f96ea6a1b5a102220b8d21

test:
  secret_key_base: 52765923bbe54bcfb2e18969958fcb12450be36dc9a5ef106d93c5ce0a3ed2098225b5fb605e5ddd990d97eb8115e03070733063b7d0508469ca379c84b47605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
